apiVersion: v1
kind: Service
metadata:
  name: bminfotrade-service
spec:
  type: NodePort
  selector:
    app: bminfotrade
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 
    nodePort: 32000
